# Generated by Django 3.2.8 on 2022-06-30 13:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Airport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.TextField(blank=True, max_length=3)),
                ('name', models.TextField(blank=True, max_length=128)),
                ('to', models.TextField(blank=True, max_length=3)),
                ('fromm', models.TextField(blank=True, max_length=3)),
            ],
        ),
        migrations.CreateModel(
            name='Flight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flight_number', models.TextField(blank=True, max_length=2048)),
                ('take_off', models.DateTimeField()),
                ('landing', models.DateTimeField()),
                ('fromm', models.ForeignKey(blank=True, max_length=3, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='going', to='flight.airport')),
                ('to', models.ForeignKey(blank=True, max_length=3, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='where', to='flight.airport')),
            ],
        ),
    ]
