# Generated by Django 3.2.8 on 2022-06-30 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flight', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='airport',
            name='code',
            field=models.CharField(blank=True, max_length=3),
        ),
        migrations.AlterField(
            model_name='airport',
            name='fromm',
            field=models.CharField(blank=True, max_length=3),
        ),
        migrations.AlterField(
            model_name='airport',
            name='name',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AlterField(
            model_name='airport',
            name='to',
            field=models.CharField(blank=True, max_length=3),
        ),
        migrations.AlterField(
            model_name='flight',
            name='flight_number',
            field=models.CharField(blank=True, max_length=2048),
        ),
    ]
